name = "glecosystem"
version = "0.1.0"
description = "A Gleam project"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.37.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
rad = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 0.7.0 and < 1.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
snag = ">= 0.3.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
